### ISSUE TITLE
在vite2中好像会报错

### ISSUE THREAD

**Issue by luocong2016** [chicAboo/v3-mhooks#1]
```
Module "url" has been externalized for browser compatibility and cannot be accessed in client code.

vue-router.esm-bundler.js:3325 Error: Module "url" has been externalized for browser compatibility and cannot be accessed in client code.
    at Object.get (v3-mhooks.js:471:11)
    at v3-mhooks.js:5900:17
```

"v3-mhooks": "^0.0.9"

**Comment by chicAboo** [comment]
> 

排查中，稍等
